'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { CalendarDays, Clock, Plus } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useAuth } from '@/hooks/use-auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { toast } from 'sonner';
import type { Deal } from '@/types';

type Event={id:string;title:string;event_type:string;starts_at:string;location?:string;deal_id?:string};
export default function CalendarPage(){
 const db=useMemo(()=>createClient(),[]),{accountId}=useAuth();const [events,setEvents]=useState<Event[]>([]),[deals,setDeals]=useState<Deal[]>([]),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[startsAt,setStartsAt]=useState(''),[type,setType]=useState('spotkanie'),[location,setLocation]=useState(''),[dealId,setDealId]=useState('');
 const load=useCallback(async()=>{const [e,d]=await Promise.all([db.from('calendar_events').select('*').order('starts_at').limit(200),db.from('deals').select('*,contact:contacts(*),company:companies(*)').eq('status','open')]);const rows=(e.data??[]) as Event[],ds=(d.data??[]) as Deal[];const derived:Event[]=[];for(const deal of ds){if(deal.meeting_at)derived.push({id:`meeting-${deal.id}`,title:`Spotkanie: ${deal.title}`,event_type:'spotkanie',starts_at:deal.meeting_at,location:deal.meeting_place,deal_id:deal.id});if(deal.next_action_at)derived.push({id:`action-${deal.id}`,title:deal.next_action||`Działanie: ${deal.title}`,event_type:'działanie',starts_at:deal.next_action_at,deal_id:deal.id});if(deal.follow_up_at)derived.push({id:`follow-${deal.id}`,title:`Ponowny kontakt: ${deal.title}`,event_type:'telefon',starts_at:deal.follow_up_at,deal_id:deal.id})}setDeals(ds);setEvents([...rows,...derived].sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at)))},[db]);useEffect(()=>{void load()},[load]);
 async function save(){if(!title.trim()||!startsAt||!accountId)return;const s=await db.auth.getSession();if(!s.data.session?.user)return;const r=await db.from('calendar_events').insert({account_id:accountId,user_id:s.data.session.user.id,title:title.trim(),event_type:type,starts_at:startsAt,location:location.trim()||null,deal_id:dealId||null});if(r.error)toast.error(r.error.message);else{toast.success('Termin dodany do kalendarza');setOpen(false);setTitle('');setStartsAt('');setLocation('');setDealId('');await load()}}
 const grouped=events.reduce<Record<string,Event[]>>((a,e)=>{const day=new Date(e.starts_at).toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long',year:'numeric'});(a[day]??=[]).push(e);return a},{});
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Kalendarz</h1><p className="text-sm text-muted-foreground">Spotkania, telefony, ponowne kontakty i terminy z kart Deal.</p></div><Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Dodaj termin</Button></div>{!events.length?<div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground"><CalendarDays className="mx-auto mb-3 h-8 w-8"/>Brak zaplanowanych terminów.</div>:Object.entries(grouped).map(([day,items])=><section key={day} className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold capitalize">{day}</h2><div className="space-y-2">{items.map(e=><Link key={e.id} href={e.deal_id?`/deals/${e.deal_id}`:'/calendar'} className="flex items-center gap-3 rounded-lg bg-muted/60 p-3 hover:bg-muted"><Clock className="h-4 w-4"/><div><p className="text-sm font-medium">{e.title}</p><p className="text-xs text-muted-foreground">{new Date(e.starts_at).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}{e.location?` · ${e.location}`:''}</p></div></Link>)}</div></section>)}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Nowy termin</DialogTitle></DialogHeader><div className="space-y-3"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nazwa spotkania, telefonu lub zadania"/><select value={type} onChange={e=>setType(e.target.value)} className="h-9 w-full rounded-md border bg-muted px-3 text-sm"><option>spotkanie</option><option>telefon</option><option>zadanie</option></select><Input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/><Input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Miejsce lub link online"/><select value={dealId} onChange={e=>setDealId(e.target.value)} className="h-9 w-full rounded-md border bg-muted px-3 text-sm"><option value="">Bez powiązanego Deala</option>{deals.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><Button className="w-full" onClick={save}>Zapisz termin</Button></div></DialogContent></Dialog></div>
}
