'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
import { AlertCircle,CalendarDays,CheckCircle2,Phone,Target } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useAuth } from '@/hooks/use-auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { Deal } from '@/types';
type Metrics={new_calls:number;meaningful_conversations:number;meetings:number;new_deals:number;moved_deals:number;applications:number};type Priority={position:number;title:string;completed:boolean};
const empty:Metrics={new_calls:0,meaningful_conversations:0,meetings:0,new_deals:0,moved_deals:0,applications:0};
export default function DashboardPage(){const db=useMemo(()=>createClient(),[]),{accountId}=useAuth();const [clock]=useState(()=>({today:new Date().toISOString().slice(0,10),now:Date.now()}));const [deals,setDeals]=useState<Deal[]>([]),[metrics,setMetrics]=useState(empty),[priorities,setPriorities]=useState<Priority[]>([1,2,3,4,5,6].map(position=>({position,title:'',completed:false})));const {today,now}=clock;
 const load=useCallback(async()=>{const s=await db.auth.getSession();if(!s.data.session?.user)return;const [d,m,p]=await Promise.all([db.from('deals').select('*,contact:contacts(*),company:companies(*),stage:pipeline_stages(*)').eq('status','open').order('next_action_at',{ascending:true,nullsFirst:false}),db.from('daily_sales_metrics').select('*').eq('metric_date',today).eq('user_id',s.data.session.user.id).maybeSingle(),db.from('daily_priorities').select('*').eq('priority_date',today).eq('user_id',s.data.session.user.id).order('position')]);setDeals((d.data??[]) as Deal[]);if(m.data)setMetrics(m.data as Metrics);const rows=(p.data??[]) as Priority[];setPriorities([1,2,3,4,5,6].map(position=>rows.find(x=>x.position===position)??{position,title:'',completed:false}))},[db,today]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function saveMetrics(next:Metrics){if(!accountId)return;const s=await db.auth.getSession();if(!s.data.session?.user)return;setMetrics(next);await db.from('daily_sales_metrics').upsert({...next,account_id:accountId,user_id:s.data.session.user.id,metric_date:today},{onConflict:'account_id,user_id,metric_date'})}
 async function savePriority(item:Priority){if(!accountId)return;const s=await db.auth.getSession();if(!s.data.session?.user)return;setPriorities(x=>x.map(v=>v.position===item.position?item:v));await db.from('daily_priorities').upsert({...item,account_id:accountId,user_id:s.data.session.user.id,priority_date:today},{onConflict:'account_id,user_id,priority_date,position'})}
 const overdue=deals.filter(d=>d.next_action_at&&+new Date(d.next_action_at)<now),without=deals.filter(d=>!d.next_action_at||!d.next_action),todayActions=deals.filter(d=>d.next_action_at?.slice(0,10)===today),meetings=deals.filter(d=>d.meeting_at?.slice(0,10)===today),priority=overdue[0]??without[0]??deals[0];
 return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Pulpit — Mój dzień</h1><p className="text-sm text-muted-foreground">Agent Sprzedaży pokazuje, co masz zrobić TERAZ.</p></div><section className="rounded-2xl border-2 border-primary/40 bg-primary/5 p-5"><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase text-primary"><Target className="h-4 w-4"/>Co masz zrobić teraz</div>{priority?<><h2 className="text-xl font-bold">{priority.next_action||`Ustal następne działanie: ${priority.title}`}</h2><p className="text-sm text-muted-foreground">{priority.contact?.name||priority.company?.name||priority.title}{priority.next_action_at?` · ${new Date(priority.next_action_at).toLocaleString('pl-PL')}`:' · brak terminu'}</p><Link href={`/deals/${priority.id}`} className="mt-4 inline-flex rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Otwórz Deal</Link></>:<p>Brak otwartych Deali.</p>}</section>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Summary icon={AlertCircle} label="Zaległe działania" value={overdue.length}/><Summary icon={Phone} label="Działania na dziś" value={todayActions.length}/><Summary icon={CalendarDays} label="Spotkania dzisiaj" value={meetings.length}/><Summary icon={CheckCircle2} label="Bez następnego kroku" value={without.length}/></div><div className="grid gap-4 lg:grid-cols-2"><List title="Pilne i zaległe" deals={overdue.slice(0,6)}/><List title="Dzisiejsze działania" deals={todayActions.slice(0,6)}/></div>
 <section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">6 najważniejszych zadań dnia</h2><div className="grid gap-2">{priorities.map(p=><div key={p.position} className="flex items-center gap-2"><input type="checkbox" checked={p.completed} onChange={e=>savePriority({...p,completed:e.target.checked})}/><span className="w-5 text-xs text-muted-foreground">{p.position}.</span><Input value={p.title} onChange={e=>setPriorities(x=>x.map(v=>v.position===p.position?{...v,title:e.target.value}:v))} onBlur={()=>savePriority(p)} placeholder="Wpisz zadanie" className={p.completed?'line-through opacity-60':''}/></div>)}</div></section>
 <section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">Wynik dzisiejszej pracy</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Counter label="Nowe telefony" value={metrics.new_calls} target={10} set={v=>saveMetrics({...metrics,new_calls:v})}/><Counter label="Wartościowe rozmowy" value={metrics.meaningful_conversations} target={10} set={v=>saveMetrics({...metrics,meaningful_conversations:v})}/><Counter label="Spotkania" value={metrics.meetings} set={v=>saveMetrics({...metrics,meetings:v})}/><Counter label="Nowe Deale" value={metrics.new_deals} set={v=>saveMetrics({...metrics,new_deals:v})}/><Counter label="Przesunięte etapy" value={metrics.moved_deals} target={1} set={v=>saveMetrics({...metrics,moved_deals:v})}/><Counter label="Wnioski" value={metrics.applications} set={v=>saveMetrics({...metrics,applications:v})}/></div></section></div>}
function Summary({icon:Icon,label,value}:{icon:typeof Phone;label:string;value:number}){return <div className="rounded-xl border bg-card p-4"><Icon className="mb-3 h-5 w-5 text-primary"/><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div>}
function List({title,deals}:{title:string;deals:Deal[]}){return <section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">{title}</h2>{!deals.length?<p className="text-sm text-muted-foreground">Brak spraw.</p>:deals.map(d=><Link key={d.id} href={`/deals/${d.id}`} className="mb-2 block rounded-lg bg-muted/60 p-3"><p className="text-sm font-medium">{d.next_action||d.title}</p><p className="text-xs text-muted-foreground">{d.title} · {d.contact?.name||d.company?.name||'bez kontaktu'}</p></Link>)}</section>}
function Counter({label,value,set,target}:{label:string;value:number;set:(v:number)=>void;target?:number}){return <div className="rounded-lg border p-3 text-center"><p className="text-xs text-muted-foreground">{label}</p><p className="my-2 text-2xl font-bold">{value}{target?`/${target}`:''}</p><div className="flex justify-center gap-2"><Button size="sm" variant="outline" onClick={()=>set(Math.max(0,value-1))}>−</Button><Button size="sm" onClick={()=>set(value+1)}>+</Button></div></div>}
